Refactor platform implementation
Add `terminal_size_of` support for additional platforms such as `wasi`.

Previously, `terminal_size_of` was unavailable on these platforms, causing the examples fail to compile:

```
error[E0425]: cannot find function `terminal_size_of` in crate `terminal_size`
  --> examples/get_size.rs:9:24
   |
 9 |         terminal_size::terminal_size_of(std::io::stdout())
   |                        ^^^^^^^^^^^^^^^^
   |
  ::: src/lib.rs:39:1
   |
39 | pub fn terminal_size() -> Option<(Width, Height)> {
   | ------------------------------------------------- similarly named function `terminal_size` defined here
   |
```